# Gunakan image resmi Python
FROM python:3.9

# Tetapkan direktori kerja
WORKDIR /app

# Salin file requirements.txt dan install dependensi
COPY requirements.txt .
RUN pip install -r requirements.txt

# Salin seluruh konten direktori ke dalam image
COPY . .

# Tetapkan variabel lingkungan untuk URL database
ENV DATABASE_URL=postgresql://postgres:123@post_air:5432/air

# Jalankan skrip Python
CMD ["python", "pyload/load_data.py"]